// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127163201_Create_table_SinhVien")]
    partial class Create_table_SinhVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MVC.Models.Book", b =>
                {
                    b.Property<string>("IdBook")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdBook");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("MVC.Models.SinhVien", b =>
                {
                    b.Property<string>("IdSV")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdBook")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdSV");

                    b.ToTable("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
