// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MVC.Models.Book", b =>
                {
                    b.Property<string>("IdBook")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdBook");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("MVC.Models.SinhVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdSV")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdBook")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
